### ISSUE TITLE
feat:Implement forget password

### ISSUE THREAD

**Issue by Niharika0104** [Yash-Parsana/CrazyCoderWebApp#13]
#### Description:
The application currently lacks the "Forgot Password" feature, which is crucial for user account recovery. This issue is to implement the necessary pages and functionality required for the "Forgot Password" feature.

#### Tasks:
1. **Create Forgot Password Page:** Develop a new page or modal for the "Forgot Password" functionality.
   - **Steps to Implement:**
     1. Design the user interface for entering email addresses for password reset requests.
     2. Implement the frontend components for the Forgot Password page/modal.
   - **Expected Behavior:** Users should be able to access the Forgot Password page/modal to initiate the password reset process.

2. **Backend Logic for Password Reset:** Develop backend logic to handle password reset requests and send reset instructions to the user's email.
   - **Steps to Implement:**
     1. Define API endpoints or backend routes to handle password reset requests.
     2. Implement logic to generate and store password reset tokens securely.
     3. Integrate with email services to send password reset instructions to users.
   - **Expected Behavior:** Upon submitting a password reset request, users should receive instructions on how to reset their passwords via email.

**Comment by Yash-Parsana** [comment]
@Niharika0104 Thank you for raising this issue you may work on this.

This feature is present in android app i have not implemeted on web app because it will not work for any random email like abcd@xyz.com and i don't want to restric that kind of emails as our main focus is not to get real authenticated mails but identify user uniquely. yet you can implement this feature.

For authentication firabase service is used, you can implement this feature by using firabase api.
refer this doc : https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email

You may find firabase related logic in services folder.

Acceptance criteria:
- Implemntation of end to end Forgot password functionality.

Teting Scope : 
- Create account with gmail account and test forgot password functionality for that account. provide screen recording with PR.

You may ask doubts on this thread if have any.

Thank you.

**Comment by Shreyash0368** [comment]
@Niharika0104 hey were u able to complete the setup for the project? im having some doubts regarding setup (the env variables)

**Comment by Yash-Parsana** [comment]
@Shreyash0368 @Niharika0104 Now it is provided in test.env file.

**Comment by Yash-Parsana** [comment]
@Niharika0104 Are you working on it, please let me know by tomorrow.

**Comment by Niharika0104** [comment]
@Yash-Parsana  I started working on it will push changes soon

**Comment by Niharika0104** [comment]
@Yash-Parsana 
const isUsernameExist = async (username) => {
    try {
        const q = query(collection(db, 'users'), where('username', '==', username));
        const users = await getDocs(q);
        let userInDb = null;
        users.forEach((doc) => {
            userInDb = {
                uid: doc.id,
                username: doc.data().username,
                status: doc.data().status,
                imgurl: doc.data().pic,
                chatfriends: doc.data().chatfriends,
            };
        });
        return userInDb;
    } catch (err) {
        throw err;
    }
};


};
query(collection(db, 'users'), where('username', '==', username));
just like how you are checking for this is there any way to findout whether email exists or not.Can you give me column name where you are storing the email ? I'm almost done with it and this is just to throw a message when the email doesn't exists
