### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by aasthakourav20** [Yash-Parsana/CrazyCoderWebApp#24]
Hevy @Yash-Parsana ,We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. 

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

Please assign this task to me .

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by vanshikab52** [comment]
A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions. It sets clear guidelines for expected behavior and helps ensure that all contributors feel safe and respected.
The repository currently lacks a CODE_OF_CONDUCT.md file which is an important resource for fostering a welcoming and inclusive environment within our community.
@Yash-Parsana  You can assign this issue to me as I'm working under GSSoC'24 as a contributor. I can add a code of conduct to this project.
Thanks

**Comment by rashiranjan22** [comment]
I am willing to work on this issue, kindly assign this issue to me under GSSOC'24

**Comment by Yash-Parsana** [comment]
@aasthakourav20 this issue is assigned to you.
